### ISSUE TITLE
Description for random email aliases

### ISSUE THREAD

**Issue by RustemB** [systemli/userli#225] opened 2020-08-03 08:01 UTC
I think this will be good idea to not be confused in your emails.

**Comment by t2d** [comment] 2020-08-03 09:14
Thank you for your comment. I think this is a duplicate of #109. Let me know, if I'm wrong.

**Closed by t2d** 2020-08-03 09:14 UTC

**Comment by RustemB** [comment] 2020-08-03 09:44
Yes-yes, it is. Sorry for dup
